CREATE TABLE Person
(
    id              INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255) NOT NULL,
    surname         VARCHAR(255) NOT NULL,
    age             INT          NOT NULL,
    city_of_living  VARCHAR(255),
    phone_of_number VARCHAR(255),
    PRIMARY KEY (age, id, name, surname)
);

INSERT INTO Person (name, surname, age, city_of_living, phone_of_number)
VALUES ('Алексей', 'Копатыч', 13, 'Москва', '+74951337'),
       ('Дмитрий', 'Соляныч', 15, 'Санкт-Петербург', '+78121337'),
       ('Владислав', 'Собяныч', 17, 'Москва', '+7495229'),
       ('Даниил', 'Бобяныч', 7, 'Москва', '+7495322');